"""A list of picks is not a list of bets, and the difference is the edge.

This project's own five-year replay is the evidence: profit factor 1.62
taking every signal on its own, 0.62 through a five-position book. No
individual trade changed. The whole difference was that signals arrive
in clusters, so a full book takes the correlated leftovers.

Every screener on the internet hands over a ranked list and lets the
reader believe the rows are separate decisions. These tests pin the
three claims that make this one different, and — more importantly — pin
the places it must refuse to answer. A concentration measure that
silently reports "independent" when it simply could not measure is worse
than none, because independence is exactly the comfortable answer.
"""
import os
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TMP = tempfile.mkdtemp(prefix="conc_")
os.environ.setdefault("MARKET_DB", os.path.join(TMP, "m.db"))
os.environ.setdefault("SCREENER_CACHE_DB", os.path.join(TMP, "c.db"))
sys.path.insert(0, str(ROOT))

import numpy as np
import pandas as pd

import concentration as cc

rng = np.random.default_rng(11)
N = 90


def build(loadings, idio=0.004, factors=None):
    r = sum(l * factors[i] for i, l in enumerate(loadings)) + rng.normal(0, idio, N)
    return list(100 * np.cumprod(1 + r))


F = rng.normal(0, 0.012, (3, N))
# One shared calendar for the synthetic book. Correlation now REQUIRES it:
# lining columns up by position is only correct when every stock traded on
# exactly the same days, and silently wrong when they did not.
DATES = [f"2026-{1 + i // 28:02d}-{1 + i % 28:02d}" for i in range(N)]
series = {}
for t in ("SEMI1", "SEMI2", "SEMI3", "SEMI4"):
    series[t] = build([1, 0, 0], factors=F)
for t in ("UTIL1", "UTIL2"):
    series[t] = build([0, 1, 0], factors=F)
series["BANK1"] = build([0, 0, 1], factors=F)
series["LONE1"] = build([0, 0, 0], idio=0.014, factors=F)
series["LONE2"] = build([0, 0, 0], idio=0.014, factors=F)

corr = cc.correlation(series, dates=DATES)
assert corr.shape == (9, 9), corr.shape

# ---- the headline number must count factors, not rows ----
enb = cc.effective_bets(corr)
assert enb is not None
assert 4.0 <= enb <= 6.0, \
    f"9 picks built from 3 factors + 2 independents should score ~5 bets, got {enb}"
print(f"effective bets: 9 picks generated by 5 underlying sources -> {enb:.1f}")

# the two extremes must be exact, or the middle means nothing
ident = pd.DataFrame(np.eye(6), columns=list("abcdef"), index=list("abcdef"))
assert abs(cc.effective_bets(ident) - 6.0) < 1e-6, cc.effective_bets(ident)
ones = pd.DataFrame(np.ones((6, 6)), columns=list("abcdef"), index=list("abcdef"))
assert abs(cc.effective_bets(ones) - 1.0) < 1e-6, cc.effective_bets(ones)
print("calibrated: 6 independent picks -> 6.0, 6 identical picks -> 1.0")

# ---- clusters must name the same trade ----
order = list(series)
groups = cc.clusters(corr, order)
by_seed = {g["seed"]: set(g["tickers"]) for g in groups}
assert by_seed.get("SEMI1") == {"SEMI1", "SEMI2", "SEMI3", "SEMI4"}, by_seed
assert by_seed.get("UTIL1") == {"UTIL1", "UTIL2"}, by_seed
assert by_seed.get("BANK1") == {"BANK1"}, by_seed
assert sum(len(v) for v in by_seed.values()) == 9, "every pick lands in exactly one group"
print(f"clusters: {len([g for g in groups if g['n'] >= 2])} multi-name groups, "
      f"every pick assigned exactly once")


# ---- marginal contribution: correlated picks must lose their place ----
def edge_flat(t):
    return (0.30, 40, "rule set")      # identical edge for everyone


rows = [{"ticker": t, "score": 90 - i} for i, t in enumerate(order)]
out = cc.marginal(rows, corr, edge_flat)
by_t = {r["ticker"]: r for r in out}

# SEMI1 is first, so nothing is committed above it: full independence
assert by_t["SEMI1"]["corr_max"] is None, by_t["SEMI1"]
assert by_t["SEMI1"]["indep"] == 1.0
assert by_t["SEMI1"]["mpc_r"] == 0.3
# SEMI2-4 duplicate it and must be discounted hard
for t in ("SEMI2", "SEMI3", "SEMI4"):
    assert by_t[t]["corr_with"] in ("SEMI1", "SEMI2", "SEMI3"), by_t[t]
    assert by_t[t]["mpc_r"] < 0.1, (t, by_t[t]["mpc_r"])
# an uncorrelated name keeps almost all of its edge despite a lower score
assert by_t["LONE1"]["mpc_r"] > 0.25, by_t["LONE1"]
print(f"marginal: identical edges, SEMI1 keeps {by_t['SEMI1']['mpc_r']}R, its three "
      f"clones keep {by_t['SEMI2']['mpc_r']}R, an independent name keeps "
      f"{by_t['LONE1']['mpc_r']}R")

# and the re-ranking actually moves them
assert by_t["SEMI4"]["score_rank"] < by_t["SEMI4"]["mpc_rank"], by_t["SEMI4"]
assert by_t["LONE1"]["mpc_rank"] < by_t["LONE1"]["score_rank"], by_t["LONE1"]
assert by_t["LONE1"]["rank_delta"] > 0
print(f"re-ranking: LONE1 moves #{by_t['LONE1']['score_rank']} -> "
      f"#{by_t['LONE1']['mpc_rank']}, SEMI4 moves #{by_t['SEMI4']['score_rank']} -> "
      f"#{by_t['SEMI4']['mpc_rank']}")

# ---- what the reader already OWNS counts as committed ----
held_out = cc.marginal([{"ticker": "SEMI1", "score": 90}], corr, edge_flat,
                       held=["SEMI3"])
r = held_out[0]
assert r["corr_with"] == "SEMI3" and r["held_overlap"] is True, r
assert r["mpc_r"] < 0.1, r
print(f"a top pick correlated with a stock you already hold drops to "
      f"{r['mpc_r']}R and names the holding: {r['corr_with']}")

# ---- REFUSALS: the whole safety argument ----

# an unmeasured edge must not be scored as an average one
def edge_none(t):
    return None


un = cc.marginal([{"ticker": "LONE1", "score": 99}], corr, edge_none)[0]
assert un["mpc_r"] is None and un["edge_source"] == "unverified", un
assert "mpc_rank" not in un, "an unverified pick must not be ranked at all"
print("a pick with no measured track record gets no contribution figure and no rank")

# too little history is not independence
short = {"A": [100, 101, 102], "B": [50, 51, 52]}
assert cc.correlation(short, dates=DATES).empty, "3 closes cannot produce a correlation"
assert cc.effective_bets(cc.correlation(short, dates=DATES)) is None
print(f"under {cc.MIN_OVERLAP} overlapping observations the answer is None, not 'independent'")

# a flat line has no correlation to anything and must be dropped, not NaN'd
flat = dict(series)
flat["FLAT"] = [100.0] * N
c2 = cc.correlation(flat, dates=DATES)
assert "FLAT" not in c2.columns, "a zero-variance series must be excluded"
assert cc.effective_bets(c2) is not None, "excluding it must not poison the matrix"
print("a zero-variance series is excluded rather than allowed to produce NaNs")

# an unmeasurable overlap must be treated as the same trade, never as new
lonely = cc.marginal([{"ticker": "NOTINDATA", "score": 90}], corr, edge_flat,
                     held=["SEMI1"])[0]
assert lonely["corr_max"] is None, lonely
assert lonely["indep"] == round(1 - cc.SAME_TRADE, 2), lonely
assert lonely["mpc_r"] < 0.3, \
    "an unmeasurable pick must not outrank a measured independent one"
print(f"a pick whose correlation cannot be measured is treated as "
      f"{cc.SAME_TRADE:g} correlated — the conservative reading, so it cannot "
      f"jump the queue by being unknown")

# ---- a MEASURED losing record must never head the board ----
# A live scan ranked a name first with a score of 77 whose own replay
# under those exact rules was -0.15R over fifteen occurrences. The score
# rates the shape of a setup; it cannot see what happened last time.
def edge_mixed(t):
    if t == "SEMI1":
        return (-0.15, 15, "this stock")     # top score, losing record
    if t == "LONE2":
        return None                           # never measured
    return (0.30, 40, "rule set")


mixed = cc.marginal([{"ticker": t, "score": 90 - i} for i, t in enumerate(order)],
                    corr, edge_mixed)
ordered = sorted(mixed, key=cc.order_key)
assert ordered[0]["ticker"] != "SEMI1", \
    "a stock with a measured losing record must not be the top pick"
assert ordered[-1]["ticker"] == "SEMI1", ordered[-1]["ticker"]
assert mixed[0]["edge_negative"] is True and mixed[0]["ticker"] == "SEMI1"
print(f"a measured loser scoring {mixed[0]['score']} moves from #1 to last, "
      f"and is flagged edge_negative")

# absence of evidence must not be punished like evidence of loss
pos = [r["ticker"] for r in ordered]
assert pos.index("LONE2") < pos.index("SEMI1"), \
    "an unmeasured setup must rank ABOVE a measured losing one"
assert ordered[0]["mpc_r"] is not None and ordered[0]["mpc_r"] > 0
print(f"unmeasured LONE2 sits at #{pos.index('LONE2') + 1}, above the measured "
      f"loser at #{pos.index('SEMI1') + 1} — no evidence is not evidence of loss")

# a positive record is never displaced by an unmeasured one
assert pos.index("SEMI2") < pos.index("LONE2") or ordered[0]["mpc_r"] > 0
s_mixed = cc.summarise(mixed, corr, groups)
assert s_mixed["losing_edge"] == 1, s_mixed
assert s_mixed["unverified_edge"] == 1, s_mixed
print(f"summary counts them separately: {s_mixed['losing_edge']} losing, "
      f"{s_mixed['unverified_edge']} unmeasured")

# ---- the summary a reader actually sees ----
enriched = cc.marginal(rows, corr, edge_flat)
s = cc.summarise(enriched, corr, groups)
assert s["n_picks"] == 9 and s["n_measured"] == 9
assert 4.0 <= s["effective_bets"] <= 6.0
assert s["biggest_cluster"]["n"] == 4
assert s["unverified_edge"] == 0
assert s["corr_days"] == cc.CORR_DAYS
print(f"summary: {s['n_picks']} picks -> {s['effective_bets']} bets, biggest "
      f"cluster {s['biggest_cluster']['n']} names at ρ {s['biggest_cluster']['mean_corr']}")

# and it survives having nothing to say
empty = cc.summarise([], pd.DataFrame(), [])
assert empty["effective_bets"] is None and empty["n_picks"] == 0
print("with no data the summary reports None rather than a comfortable number")

print("\nALL CONCENTRATION TESTS PASSED")

# ---- one company, one row ----
# De-duplication was by ticker string, which is not company identity. BT
# Group reaches the universe as BT-A.L and BTL.XC, Logitech as LOGI and
# LOGN.SW, Shell as SHEL and SHEL.L. Different strings, so both survived
# and the board showed the same setup twice with near-identical numbers.
# A reader working down the list buys one position believing they bought
# two. That is worse than the correlation problem above, because it is
# not correlation — it is identity.
PAIRS = [
    (("BT Group PLC", "BT-A.L"), ("BT GROUP PLC ORD 5P", "BTL.XC")),
    (("Logitech International S.A.", "LOGI"), ("Logitech International SA", "LOGN.SW")),
    (("SHELL PLC", "SHEL"), ("SHELL PLC ORD EUR0.07", "SHEL.L")),
    (("Unilever PLC", "UL"), ("Unilever PLC ORD 3 1/9P", "ULVR.L")),
    (("Nestle S.A.", "NESN.SW"), ("Nestle SA ADR", "NSRGY")),
]
for (n1, t1), (n2, t2) in PAIRS:
    assert cc.company_key(n1, t1) == cc.company_key(n2, t2), \
        f"{t1} and {t2} are the same company: " \
        f"{cc.company_key(n1, t1)!r} vs {cc.company_key(n2, t2)!r}"
print(f"{len(PAIRS)} cross-listing pairs resolve to one company each")

# and genuinely different companies must NOT be merged — the normaliser
# is the risk here: substring stripping once turned "Republic Services"
# into "republicrvices" by eating the " se", which is silent until two
# mangled names happen to collide
DISTINCT = [("MGM Resorts International", "MGM"), ("Marriott International, Inc.", "MAR"),
            ("Republic Services, Inc.", "RSG"), ("Waste Connections, Inc.", "WCN"),
            ("Waste Management, Inc.", "WM"), ("CSX Corporation", "CSX"),
            ("Norfolk Southern Corporation", "NSC"),
            ("Philip Morris International Inc.", "PM"),
            ("British American Tobacco p.l.c.", "BTI")]
keys = [cc.company_key(n, t) for n, t in DISTINCT]
assert len(set(keys)) == len(keys), f"false merge among distinct companies: {keys}"
# the exact strings that were being mangled, pinned literally — a length
# heuristic would pass "csx", which is legitimately three characters
assert cc.company_key("Republic Services, Inc.", "RSG") == "republicservices"
assert cc.company_key("Waste Connections, Inc.", "WCN") == "wasteconnections"
assert cc.company_key("Waste Management, Inc.", "WM") == "wastemanagement"
assert cc.company_key("British American Tobacco p.l.c.", "BTI") == "britishamericantobacco"
assert cc.company_key("CSX Corporation", "CSX") == "csx"
print(f"{len(DISTINCT)} distinct companies stay distinct, names intact")

# a row with no usable name falls back to its ticker, never merging blind
assert cc.company_key("", "ORPHAN.X") == "t:ORPHAN"
assert cc.company_key(None, "A.B") != cc.company_key(None, "C.D")
print("a nameless row falls back to its ticker rather than merging blind")

# the survivor is the line a reader can actually fill
rows = [{"ticker": "BTL.XC", "name": "BT GROUP PLC ORD 5P", "dollar_vol_m": 4.0},
        {"ticker": "BT-A.L", "name": "BT Group PLC", "dollar_vol_m": 30.0},
        {"ticker": "LOGN.SW", "name": "Logitech International SA", "dollar_vol_m": 20.0},
        {"ticker": "LOGI", "name": "Logitech International S.A.", "dollar_vol_m": 180.0},
        {"ticker": "MGM", "name": "MGM Resorts International", "dollar_vol_m": 200.0}]
kept, dropped = cc.dedupe_listings(rows)
assert [r["ticker"] for r in kept] == ["BT-A.L", "LOGI", "MGM"], \
    [r["ticker"] for r in kept]
assert len(dropped) == 2
for d in dropped:
    assert d["duplicate_of"] in ("BT-A.L", "LOGI"), d
    assert "same company as" in d["why_not"], d["why_not"]
print(f"the more liquid line survives each pair; the other is dropped WITH a "
      f"reason: {dropped[0]['why_not'][:60]}...")

# nothing is lost silently: every input row is either kept or reported
assert len(kept) + len(dropped) == len(rows)
print("every row is either kept or reported dropped — none vanish")

print("\nALL DE-DUPLICATION TESTS PASSED")


# ---- the calendar bug: position is not a date ----
# The first version dropped each ticker's index and lined the columns up by
# position. A London listing sitting out three UK bank holidays the NYSE
# traded was enough to turn a correlation of 1.00 into 0.49 — the book
# reporting 1.76 independent bets where it held one. Two series of
# different lengths were worse: identical prices scored -0.006, and the
# check told the reader a stock they already owned was "a genuinely new bet".
_base = build([1, 0, 0], factors=F)
_holidays = {7, 23, 61}                     # days the second listing did not trade

# same company, two listings, one calendar with gaps
_gapped = [None if i in _holidays else v for i, v in enumerate(_base)]
_pair = cc.correlation({"US": _base, "LSE": _gapped}, dates=DATES)
assert not _pair.empty, "a few missing days must not make it unmeasurable"
_rho = float(_pair.at["US", "LSE"])
assert _rho > 0.99, f"the same price path must correlate at ~1.00, got {_rho:.2f}"
assert abs(cc.effective_bets(_pair) - 1.0) < 0.05, cc.effective_bets(_pair)
print(f"one company on two calendars correlates at {_rho:.2f} and counts as "
      f"{cc.effective_bets(_pair):.2f} bets, not two")

# and without dates a multi-ticker frame is refused rather than guessed
_blind = cc.correlation({"US": _base, "LSE": _base})
assert _blind.empty, \
    "with no calendar the correlation is unknowable and must not be invented"
print("with no dates the correlation is refused, not computed off row position")

# unequal lengths can no longer be lined up end-to-start
_mixed = cc.correlation({"US": _base, "CUT": [None] * 30 + _base[30:]}, dates=DATES)
# not "empty OR correct": an aligner regression that returns an empty
# frame would pass that, and empty means the check silently stops
# measuring overlap at all
assert not _mixed.empty, "a series starting later must still be comparable"
assert float(_mixed.at["US", "CUT"]) > 0.99, float(_mixed.at["US", "CUT"])
print("a shorter series is aligned to its own dates, never to another's")

print("\nCALENDAR ALIGNMENT PINNED")


# ---- the bets figure counts stocks, and says so ----
# Weighting this by position size was tried and reverted: the
# principal-components form of Meucci's measure RISES as a book
# concentrates (four names in two correlated pairs score 2.31 with 99% of
# the money in one of them, against 1.04 held evenly), and a
# diversification number that improves as you concentrate is worse than
# none. The measure stays a property of the names held, and the sentence
# built from it has to say that.
_four = {"NV": build([1, 0, 0], factors=F), "AM": build([1, 0, 0], factors=F),
         "KO": build([0, 1, 0], factors=F), "PE": build([0, 1, 0], factors=F)}
_c4 = cc.correlation(_four, dates=DATES)
_bets = cc.effective_bets(_c4)
assert _bets is not None and 1.5 < _bets < 2.6, _bets
print(f"four names driven by two factors count {_bets:.2f} bets")

import inspect as _inspect
assert "weights" not in _inspect.signature(cc.effective_bets).parameters, \
    "if this grows a weights argument, the caller's sentence must change too"
import pretrade as _pt
_src = _inspect.getsource(_pt.check)
assert "rather than how much of each" in _src, \
    "the reader must be told the figure counts holdings, not euros"
print("the caller states that it counts holdings rather than position sizes")

print("\nBETS BASIS PINNED")


# ---- shrinkage: opt-in, valid, and provably closer to the truth ----
# 40-60 overlapping sessions is not much data for a pairwise correlation —
# a pair with no real relationship still shows a nonzero sample number from
# noise alone. shrink_correlation() pulls the matrix toward "unrelated" by
# a data-driven amount instead of trusting every entry at face value.

# it must not change the default path — SAME_TRADE and effective_bets()
# were tuned against the raw matrix, and reviving a "cruder" number by
# accident here would be the exact failure this project keeps re-finding
_raw = cc.correlation(series, dates=DATES)
_default = cc.correlation(series, dates=DATES)
assert _default.equals(_raw), "correlation() must stay unshrunk unless asked"
print("shrink defaults to off: correlation() is unchanged unless shrink=True")

# the shrunk matrix must still BE a correlation matrix
_shrunk = cc.correlation(series, dates=DATES, shrink=True)
assert _shrunk.shape == _raw.shape
_sv = _shrunk.to_numpy()
assert np.allclose(np.diag(_sv), 1.0, atol=1e-8), np.diag(_sv)
assert np.allclose(_sv, _sv.T), "not symmetric"
assert np.all(np.linalg.eigvalsh((_sv + _sv.T) / 2) >= -1e-8), "not positive semi-definite"
print("shrunk matrix is still a valid correlation matrix: unit diagonal, symmetric, PSD")

# every off-diagonal entry must move toward zero, never away from it —
# this is what "shrinkage toward independence" has to mean, entry by entry
_rv = _raw.to_numpy()
_off = ~np.eye(_rv.shape[0], dtype=bool)
assert np.all(np.abs(_sv[_off]) <= np.abs(_rv[_off]) + 1e-9), \
    "a shrunk entry grew in magnitude instead of moving toward zero"
assert np.any(np.abs(_sv[_off]) < np.abs(_rv[_off]) - 1e-9), \
    "shrinkage had no measurable effect on this fixture"
print("every off-diagonal entry moved toward zero, none moved away from it")

# and it must actually be a better estimate, not just a smaller number —
# proven the way this project proves everything: on held-out data. Build
# KNOWN true correlation structures (two blocks at different true rho, plus
# cross-block noise), estimate each from one 50-session sample (matching
# MIN_OVERLAP), and check the shrunk estimate sits closer on average to an
# INDEPENDENT second sample from the same structure than the raw one does.
# A single trial is noisy enough to go either way — six different seeds at
# 300 trials each all showed the same 2-4% mean reduction in error, so the
# assertion is on the mean across many trials, not a per-trial coin flip.
_rng2 = np.random.default_rng(2026)
_T, _raw_errs, _shr_errs = 50, [], []
for _trial in range(300):
    _n = _rng2.integers(4, 12)
    _true = np.eye(_n)
    _rho1 = _rng2.uniform(0.3, 0.8)
    _rho2 = _rng2.uniform(0.0, 0.3)
    _b = _n // 2
    for _i in range(_n):
        for _j in range(_i + 1, _n):
            if _i < _b and _j < _b:
                _r = _rho1
            elif _i >= _b and _j >= _b:
                _r = _rho2
            else:
                _r = _rng2.uniform(-0.1, 0.1)
            _true[_i, _j] = _true[_j, _i] = _r
    _ev, _evec = np.linalg.eigh(_true)
    _true = _evec @ np.diag(np.clip(_ev, 1e-6, None)) @ _evec.T
    _d = np.sqrt(np.diag(_true))
    _true /= np.outer(_d, _d)
    _L = np.linalg.cholesky(_true + 1e-9 * np.eye(_n))
    _train = _rng2.standard_normal((_T, _n)) @ _L.T
    _test = _rng2.standard_normal((_T, _n)) @ _L.T
    _tickers = [f"S{_i}" for _i in range(_n)]
    _tdates = [f"d{_i}" for _i in range(_T)]
    _train_series = {t: list(100 * np.cumprod(1 + 0.01 * _train[:, i]))
                     for i, t in enumerate(_tickers)}
    _test_series = {t: list(100 * np.cumprod(1 + 0.01 * _test[:, i]))
                    for i, t in enumerate(_tickers)}
    _raw_c = cc.correlation(_train_series, dates=_tdates).to_numpy()
    _shr_c = cc.correlation(_train_series, dates=_tdates, shrink=True).to_numpy()
    _hold_c = cc.correlation(_test_series, dates=_tdates).to_numpy()
    _raw_errs.append(np.linalg.norm(_raw_c - _hold_c, 'fro'))
    _shr_errs.append(np.linalg.norm(_shr_c - _hold_c, 'fro'))
_mean_raw, _mean_shr = np.mean(_raw_errs), np.mean(_shr_errs)
assert _mean_shr < _mean_raw, \
    (f"shrinkage should beat the raw sample correlation against held-out "
     f"data on average at {_T} sessions: raw {_mean_raw:.4f}, shrunk {_mean_shr:.4f}")
print(f"against independent held-out data across 300 synthetic trials, the "
      f"shrunk matrix's mean error was {_mean_shr:.4f} against the raw "
      f"matrix's {_mean_raw:.4f} — a {100*(_mean_raw-_mean_shr)/_mean_raw:.1f}% "
      f"reduction, at {_T} sessions")

print("\nSHRINKAGE PINNED")
